### ISSUE TITLE
Figure out how the kanban board works

### ISSUE THREAD

**Issue by AureumChaos** [AureumChaos/LEAP#1]

**Comment by piprrr** [comment]
Here's a shortcut for the board: https://github.com/AureumChaos/LEAP/projects/1

it's kinda weird that you can create *more than one* board per github project.  That's a different model from gitlab, which only allows for a single kanban board; moreover, gitlab boards piggy-back on their issue tracking system, whereas github keeps the issues separate from project boards.  Interesting.

**Comment by AureumChaos** [comment]
I guess having more than one board gives us more options, although I doubt
we'll use more than one anytime soon.

Effective Python doesn't seem to have much to say about modules, but
reading the Cookbook gave me a solution to a problem that was giving me all
sorts of grief, so that's good.

Jeff

**Comment by piprrr** [comment]
On Fri, Oct 12, 2018 at 10:32 AM Jeff Bassett <notifications@github.com>
wrote:

> I guess having more than one board gives us more options, although I doubt
> we'll use more than one anytime soon.
>

True.  I can easily envision multiple projects sharing the same github, so
it's nice that that flexibility exists.  I still find gitlab's solution of
piggy-backing kanban functionality on top of the issue tracking system
simpler and a little more elegant.  If more than one project shares a
single gitlab repository, you can always use labels to differentiate
tasks.  Admittedly, this is moot since we're using github, and we'll only
be using the one project board, anyhoo.  I'm still enjoying comparing the
two different git web facades.


> Effective Python doesn't seem to have much to say about modules, but
> reading the Cookbook gave me a solution to a problem that was giving me all
> sorts of grief, so that's good.
>

What was the problem giving you grief?

Meanwhile, I've pushed *Functional Programming in Python* on my "to read"
list since it's short, and has relevant material that may "prime the pump"
for reading the appropriate parts of *Effective Python* and the *Python
Cookbook*. (I can pass along the softcopy if you need it.)

I tell ya, I'm really excited about these new python features such that I'm
very confident that a much leaner and meaner LEAP design is possible.
Moreover, we'll be doing things that no other python-based EC library is
doing as many of the competitors were written with 2.x in mind, or are
otherwise barely cognizant of the python 3 feature set.

Speaking of which, here's the github for inspyred:
https://github.com/aarongarrett/inspyred .  I'd be curious to learn your
opinion of it.  Again, he gets his, um, "inspiration" from Ken's book, so
there's that.

-- Mark
