### ISSUE TITLE
Mult-objective benchmarks

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#107]
- [x] ZDT suite
- [x] Deb's 3-function/2-objective generator

**Comment by lukepmccombs** [comment]
I have candidates for the ZDT function suite on my fork. They are all functional, although the comments, specifically the latex math for the newer functions, needs to be updated appropriately. I'll update those too when I can.

A few for example:
ZTD1 as the base, ZTD4 since its deceptive, and ZTD5 since its a binary problem.
Note that while ZTD5's results are an optimal front, it is not the global optima.

![output](https://user-images.githubusercontent.com/82639211/210855002-e0651c74-214c-410e-9d8e-00a3cb1b946c.png)
![output1](https://user-images.githubusercontent.com/82639211/210855003-55ced268-ad80-49c3-8083-476ca7f3771b.png)
![output2](https://user-images.githubusercontent.com/82639211/210855006-f7a6ac99-5bf3-456f-bb75-c5184aa68e97.png)

**Comment by markcoletti** [comment]
@lukepmccombs has added the new benchmarks, which have been folded into `develop`, so I will mark this as completed.
