### ISSUE TITLE
Variable size pool?

### ISSUE THREAD

**Issue by grudloff** [AureumChaos/LEAP#114]
Hello! Is there a way to have a sink that collects individuals until the source is empty, for example, when `naive_cyclic_selection` completes a single run over the parents? I am interested in reproducing some algorithms that don't follow your fixed `pool(size = pop_size*BROOD_SIZE)` workflow.

Some pointers would be greatly appreciated. Thanks!

**Comment by SigmaX** [comment]
Do I understand correctly that

- You want to make an algorithm were pattern of putting `ops.pool(size=SOME_VALUE)` at the end of the operator pipeline to "pull" individuals through to create the next population wont meet your needs
  - Because, for example, the algorithm may have a variable populations size or some such.
  
- So it would be convenient to have some variation on `ops.pool` that says "pull everything you've got through the pipeline until a `StopIteration` is reached?"

So where right now we do things like this to create new populations:

```python
import sys, os
import toolz

from leap_ec.individual import Individual
from leap_ec.binary_rep.ops import mutate_bitflip
import leap_ec.ops as ops

pop = [ Individual([0, 0]),
        Individual([0, 0]),
        Individual([0, 0]) ]

new_pop = toolz.pipe(iter(pop),
                     mutate_bitflip(expected_num_mutations=2),
                     ops.pool(size=3))
list(new_pop)
```

You'd like to be able to do something like this?

```python
new_pop = toolz.pipe(iter(pop),
                     mutate_bitflip(expected_num_mutations=2),
                     ops.pool(size='ALL'))
```

or even (more obscurely)

```python
new_pop = toolz.pipe(iter(pop),
                     mutate_bitflip(expected_num_mutations=2),
                     list)
```

Right now this won't work, because our operators use `yield` to return individuals, and since Python 3.7 `yield` issues a `RuntimeError` instead of a `StopIteration` when it reaches the end of its input.  To support this, it [looks like](https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app) we'd need to go through LEAP's operators and add explicit logic to throw `StopIteration`s.

But am I understanding your needs correctly?  And I'm curious to hear @piprrr 's thoughts.

**Comment by SigmaX** [comment]
A a proof of concept, this operator works---except for the ghastly `except RuntimeError`, which is far too broad:

```python
def pool_all(next_individual):
    pool = []
    while True:
        try:
            x = next(next_individual)
            pool.append(x)
        except RuntimeError:
            return pool
```

**Comment by piprrr** [comment]
One alternative from the same StackOverflow article would be to put something like this in *all* the pipeline generator`ops`:

```python
try:
    yield next(seq)
except StopIteration:
    return
```
I'm not sure how I feel about that.  It may be that we'll have to put this as an edge or corner case where your `RuntimeError` approach would be a good "recipe" for this scenario since almost no one is going to want this.   I think.  Maybe? (And, yes, I'm advocating for making this a recipe in our nearly empty cookbook.)

**Comment by grudloff** [comment]
Hello @SigmaX and @piprrr, thanks a lot for the great support! @SigmaX I was referring mainly to having a variable pool size to be then shopped down to a fixed population size, but essentially the problem is the same. 

There is another alternative to solve the `yield` issue, by replacing the current
```python
while True:
    x = next(next_individual)
    yield x
```
with 
```python
for x in next_individual:
     yield x
```
This evades the yield problem as the `for` loop handles the `StopIteration` and stops the iteration. And I believe it maintains the current behavior without any issue.

PD:
For the yield of pairs a `for` loop with `zip()` can be used.

PD2: 
Completely unrelated but I believe 
```python
while True:
        yield next(itr)
```
can be replaced by 
```python
yield from itr
```

**Comment by piprrr** [comment]
@grudloff , we just had a discussion about this issue, and we're curious about those algorithms you were trying to reproduce.  Could you please point us at them?  I think once we have an idea of what you're trying to emulate, we can better help you.

Meanwhile, I've been thinking of your original question: " Is there a way to have a sink that collects individuals until the source is empty?"  With that in mind, consider the following code:

```python
offspring = pipe(parents,
                 ops.cyclic_selection,
                 ops.clone,
                 mutate_bitflip,
                 ops.evaluate,
                 ops.pool(size=len(parents)))
```
This seems to do what you wanted.  That is, `cyclic_selection` will pull through one-by-one each of the individuals in `parents`, then `ops.pool(size=len(parents))` will pull through at most one cycle, or all the individuals in the original population.  That is, it will have the effect of seeing all the individuals once and only once as if you were iterating on a `for` loop for `parents`.

Here's a more detailed example:

```python
from toolz import pipe
from pprint import pprint
from leap_ec.individual import Individual
import leap_ec.ops as ops
from leap_ec import probe

def simple_mutation(next_individual):
    while True:
        ind = next(next_individual)
        ind.genome[0] += 19 # add some goofy arbitrary number
        yield ind

pop = [Individual([0]), Individual([1])]

offspring = pipe(pop,
                 ops.cyclic_selection,
                 ops.clone,
                 simple_mutation,
                 probe.print_individual, # print just the genomes to verify
                 ops.pool(size=len(pop)))

pprint(offspring)```

Which produces:

```
[19]
[20]
[Individual([19], None, None), Individual([20], None, None)]
```

So we see the "[19]" of the first selected individual's offspring followed by "[20]" of the second.  And then the returned cloned population is shown mirroring the same sequence. Does that help?

**Comment by SigmaX** [comment]
@grudloff your observation that a simple `for` loop avoids the `RuntimeException` is a good one!

I took a dip into following your suggestion.  I experimented with adding a `size='auto'` logic to `ops.pool()`.  Then a typical example pipeline might look like this:

```python
pipeline=[
       ops.tournament_selection(k=2),
       ops.clone,
       mutate_binomial(std=1.5, bounds=[problem.bounds]*l,
                       expected_num_mutations=1),
       ops.evaluate,
       ops.pool(size='auto'),
       # Some visualization probes so we can watch what happens
       probe.PlotTrajectoryProbe(xlim=problem.bounds, ylim=problem.bounds,
              contours=problem),
       probe.PopulationPlotProbe(),
       probe.FitnessStatsCSVProbe(stream=sys.stdout)
   ]
```

Looking backwards up the pipeline, `mutate_binomial()` is no problem: if we replace its internal `while True` loop with `for` like you suggest, it will just mutate individuals until it exhausts its input.

The problem is the `ops.tournament_selection` operator.  Tournament selection doesn't just transform each of its inputs and then exhaust.  Instead, it generates as many parents as we request from it, via eternal repeated tournaments.

So running this pipeline (ex. by plugging it into `examples/int_rep.py`) causes an infinite loop.

I don't see how to fix this except by moving the hard-coded `size` value upstream to the selection operator, with something like `ops.tournament_selection(k=2, max_individuals_produced=pop_size)`.  But that's a bit clunky and doesn't seem to provide much advantage over `ops.pool(size=pop_size)`.

---

So I think my conclusion is the same as @piprrr : if you can give us a concrete example of what you'd like to do, we can try to reason about how to adapt the framework to fit it.  It's hard to see a solution in the abstract, though, so I'm back-burnuring this issue for now.

**Comment by grudloff** [comment]
Hello @piprrr and @SigmaX. I was originally thinking of an operation that yields a variable number of child, like the following:

```python
@curry
@iteriter_op
# yield permutations of each genome stochastically
def stoc_swap(individual_itr: Iterator, p_swap: int = 0.5) -> Iterator:
    for individual in individual_itr:
        genome_perm = permutations(individual.genome)
        # always yield original
        next(genome_perm)
        yield  individual 
        for genome in genome_perm:
            if random.random() < p_swap: 
                individual = individual.clone()
                individual.genome = list(genome)
                yield individual 
```

But it turns out I misunderstood the original algorithm and this isn't the correct operation, instead only one permutation is tried and the best between the two is selected. I am really sorry for wasting your time with this, my sincere apologies.

**Comment by SigmaX** [comment]
@grudloff No apology necessary!  We're always happy to consider new "data points" that stretch the framework to cover and may call for some refactoring.

Closing, since there appears to be no immediate demand for this feature.
