### ISSUE TITLE
Possible birth counter race condition

### ISSUE THREAD

**Issue by markcoletti** [AureumChaos/LEAP#244]
Where I explore the possibility that there is a race condition for calculating the birth counter in the ASEA

**Comment by markcoletti** [comment]
Moved this to the backlog as it's not a priority.  Though it's likely that there may be a race condition for involving `DistributedIndividual`'s `birth_id`, I suspect it's somewhat mitigated by how we currently use Dask in both the asynchronous and synchronous implementations.  However, I will be occasionally assessing run results for evidence of such race conditions, as possibly evidenced by duplicate or missing birth ids.

**Comment by markcoletti** [comment]
Essentially had observed duplicate or skipped IDs and reasoned that this was likely due to a race condition.

Actually, the initial population should have birth IDs automatically assigned when created.  It's just that when we fall into the the offspring creation loop that we start counting from where we left off with the last ID from the initial population.  And then there's the bookkeeping for whether we want non-viable individuals to count towards the birth budget.

**Comment by lukepmccombs** [comment]
I don't see any duplicate birth IDs, but I think I know what might be the cause of the skipped IDs. If you use the crossover operator, but only pool 1 individual at a time in the pipeline, it discards the other individual. But it was still "birthed", and the ID counter is incremented for it. A pretty quick test of changing the pool size to 2 resulted in the highest observed ID at the end of the evolution process being 1 less than the total number observed (i.e. the 0-indexed max as you would get with `itertools.count`).

**Comment by markcoletti** [comment]
The other individual curing crossover is not discarded, but is rather sent the next time that operator is pulsed.  That's why it has two different `yield` statements.  This is actually a significant difference between LEAP and DEAP in that DEAP *does* discard one of the offspring, which introduces a source of genetic drift.

**Comment by lukepmccombs** [comment]
That is the case for the by-generational pipeline, but I don't believe it is so for the steady state pipeline. Each time the algorithm goes to produce offspring, the pipeline is called again, reinstantiating the crossover operator's local frame. If you produce multiple at once, they will all come from the same instance and receive the successive children, but not so between calls.

**Comment by markcoletti** [comment]
I don't think the crossover operator is re-instantiated between pipeline pulses; the operators are already instantiated when passed in via the `offspring_pipeline` argument to `steady_state`.  You could probably cons up a quick test to observe what actually happens.

**Comment by markcoletti** [comment]
Thanks for the test snippet!  That's disappointing.  (And fortunate that I don't generally use crossover!). We can discuss on Slack the possible workarounds.  This may also have ramifications for other pipeline operators, though I can't think offhand of likely candidates.

**Comment by lukepmccombs** [comment]
Here is an example higher order function that could fix it. It keeps children in a local deque before they are yielded. The way yield works will prevent it from making excess children (only continuing execution when requested for the next), and on future calls any leftover children are yielded on that run instead.

```
def dummy_crossover() -> Iterator:
    next_children = deque()
    
    @iteriter_op
    def _crossover_op(next_individual):
        while True:
            for ind in next_children:
                yield ind
            parent1 = next(next_individual)
            parent2 = next(next_individual)
            next_children.extend((parent1, parent2))
        
    return _crossover_op
```

**Comment by SigmaX** [comment]
@lukepmccombs Oh, yikes.  So, am I understanding that we may have an issue where our code assumes that `tools.curry()` acts like a closure—returning a single instance so if it's called multiple times we can yield multiple values—but in reality it ends up re-instantiating every time it is executed?

I just reviewed your PR, but if it's aiming to solve the observation here I'm not sure why the `deque` is needed.  What about a closure that behaves the way the `@curry` was intended to?

```python
def dummy_crossover():
    next_children = deque()
    
    @iteriter_op
    def _crossover_op(next_individual) -> Iterator:
        while True:
            while next_children:
                yield next_children.popleft()
            parent1 = next(next_individual)
            parent2 = next(next_individual)
            yield parent1
            yield parent2
        
    return _crossover_op
```

**Comment by SigmaX** [comment]
Copying my comment from #273 for summary purposes:

The observation is that when our crossover operators are used in a steady-state population model specifically, then because we are generating a single offspring at a time in each evolutionary step, we end up losing the functionality of generating a pair of two offspring for each pair of parents.

So the original operators work as designed—one instance will correctly generate two complementary offspring when you call it twice. The problem is that we are only calling the pipeline once in each step for steady-state algorithms, so the second offspring gets created but never yielded (thus inflating our birth count).

**Comment by lukepmccombs** [comment]
The issue is present in all of our pipelines, just most prevalent in steady state. It occurs when the pipeline is made to collect an odd number of individuals, which is almost always 1 in the case of steady state. An individual is birthed by the crossover operator, but discarded before it is consumed by a pipeline operator further down. For example, if you were pooling a population of size 5, like in the neural network cartpole example, 1 in 6 births would be discarded.

The operators are called once per pipeline execution. That is every evaluation (and subsequent offspring birthing) for steady state, and once per generation for the generational ea. It is possible to bypass this issue for either by just using an even numbered pool, but in the case of steady state that results in an explosion of individuals in queue.

**Comment by markcoletti** [comment]
This issue is resolved.  Closing.
