### ISSUE TITLE
Add ability to track lineage

### ISSUE THREAD

**Issue by markcoletti** [AureumChaos/LEAP#61]
Add the capability to either have parents remember their offspring, or offspring remember their parents, thus making possible lineage analysis.

This will likely entail extending the existing clone() pipeline operator, or adding a new clone operator to append this information to individuals.

**Comment by lukepmccombs** [comment]
Would this require modification of crossover operators too? Or would only one, the cloned individual, be considered the primary parent?

**Comment by markcoletti** [comment]
> Would this require modification of crossover operators too? Or would only one, the cloned individual, be considered the primary parent?

Nope.  The cloned individual isn't the primary parent, per se, but is rather an inchoate offspring.  The first step in creating any offspring is to clone a parent, essentially yielding a base upon which mutation, and possibly crossover, can be applied to create a unique individual.

So, since *all* offspring spring forth from a clone operator, that operator is a good place to manage lineages.  I'm tempted to just add lineage tracking as a default as I see adding a separate clone operator or extending the current one as maybe adding undue complexity.

**Comment by lukepmccombs** [comment]
I foresee some problems with how we implement this though. Direct references are likely a no-go, since python would drag the whole reference tree along for the ride when doing distributed. Its possible to override that behavior, but it would take some lower level modifications of the Individual class that I am unsure about and believe would hurt the tree's usability.

I think IDs are a better option. A global state for them could be possible since most operators happen in a single thread, but UUIDs are more stable and distributed friendly.

**Comment by markcoletti** [comment]
Even with a distributed setup, the individuals tend to live in a central process space, which mitigates the issue of using direct references.  Moreover, for distributed evaluation only the genome is sent out anyway, and not the whole individual.

However, a different problem may arise when doing checkpointing and restarts.  There I can see using something like a UUID that outlives the run-time as being useful for lineage tracking.  In which case, we may consider moving the UUID management from the `DistributedIndividual` to `Individual` such that every individual is guaranteed to have a UUID that could be exploited for the purposes of checkpoints and restarts.

**Comment by markcoletti** [comment]
We have basic support for lineage tracking via `Individual.clone()` and with support forthcoming for crossover operators.  I'm capturing thoughts that @lukepmccombs and I had regarding further work on this.

First, used of a `OrderedSet` for parents since additional parents will be added during crossover, and that offers a convenient way to add second parents due to crossover.  The order is useful because presumably the first parent is via cloning and the second inherited via any subsequent crossover.

* an ordered set class: https://pypi.org/project/ordered-set/ , though not thrilled with adding yet another dependency

**Comment by lukepmccombs** [comment]
When implementing lineage tracking for crossover operators, a problem arises with upkeeping the bidirectional tree of parents and children. In the crossover operators, we create the children by directly modifying the parents, or more accurately "children" are created by the clone operator and they undergo recombination in crossover operators where the parent connections get interweaved.

The problem is, for lightening complexity we keep only the uuids from parents and children. We can extend the parents list for each child in the crossover operators, but we can't update the corresponding parents without directly accessing the parent object. It should be possible to reconstruct the lineage tree using only the parents list, but it would be preferable to keep both.

We can't use the direct parent references because the entire tree gets dragged along during pickling / unpickling. Which I am certain happens to the full individual during distributed evaluation. We can override pickling behavior to sever the link, but that isn't a graceful solution.

**Comment by markcoletti** [comment]
We had left off the conversation on needing a link to parents to update their offspring, which has pickling ramifications.  I suspect we can use policy whereby a given individual only knows of its immediate parent or parents and of its clones.  With that in mind:

* any of the clones can gain an additional parent via crossover
* a given individual can have zero or more clones and zero, one, or two parents
* zero parent individuals are just from the initial random population

**Comment by markcoletti** [comment]
Given the inconsistency between tracking parents and children due to crossover, we will remove tracking children and only track parents.  In post mortem analysis the entire lineage can be built from the parent links.
