### ISSUE TITLE
Add bounds enforcement pipeline operators

### ISSUE THREAD

**Issue by markcoletti** [AureumChaos/LEAP#64]
Currently, some hard-bounds enforcement is tightly integrated within perturbation pipeline operators.  However, this can be decoupled into a separate bounds operator.  

There can be a bounds operator that clips values and another one that flags an individual for bounds constraints violations.

**Comment by SigmaX** [comment]
Discussion with @markcoletti: we already have a consistent pattern for doing this with the existing `hard_bounds` argument approach.  Also, logic for dealing with constraint violations can be very operator specific: for example, some strategies do re-sampling rather than clamping in a particular way.  So it does not make sense to separate bounding into a separate operator in all cases.
