### ISSUE TITLE
Reorganize modules and sub-packages

### ISSUE THREAD

**Issue by piprrr** [AureumChaos/LEAP#69]
As LEAP has reached a critical level of complexity, we will reorganize the code to simplify understandability:

Move representation specific things to sub-packages.  E.g., binary ops to binary and real ops to real.  These subpackages will include initializers, decoders, and problems.

Also, break up core into separate modules.

**Comment by SigmaX** [comment]
I've gotten a little preview of what this will be like working on #67.  Right now it's pleasant, because I've just been writing things like

```Python
from leap_ec import core, ops
from leap_ec.executable import decoder, problem, phenotype
```

I do note that the `import`s will be a bit more complicated in cases where we depend on different `ops` modules in the same package, though.  For example:

```Python
from leap_ec import ops
from leap_ec.real.ops import gaussian_mutate
from leap_ec.executable import decoder, problem, phenotype
```

Not sure there's any real downside here.  Just pointing it out.

**Comment by piprrr** [comment]
I hear you with regards to more complex `import` s, however we can possibly get clever with `__init__.py` in that we can have it import some of the "always imported" packages as syntactic sugar.  (At least I *think* we can abuse `__init__.py` in that way.)
