### ISSUE TITLE
Does LEAP support genetic programming?

### ISSUE THREAD

**Issue by nbro** [AureumChaos/LEAP#86]
My question is in the title. After a quick search on the documentation page with the keywords "genetic programming", there does not seem to be any support for GP, which seems to be confirmed by the Future Work section of [the associated paper](https://www.osti.gov/servlets/purl/1649229). From [here](https://github.com/AureumChaos/LEAP/blob/develop/CHANGELOG.md), it seems that now some version of LEAP supports [Cartesian genetic programming](https://en.wikipedia.org/wiki/Cartesian_genetic_programming). Not sure what it really is, because I've never used it.

**Comment by SigmaX** [comment]
Hi @nbro, thanks for the question!

You're correct—the development branch of LEAP now has a CGP implementation, which is the first variant of GP we've tackled.

We've been giving a lot of thought to how to make sure LEAP can support other kinds of GP seamlessly (in particular, we've been comparing different design ideas for how to best facilitate _parsimony pressure_, which is a must-have for many forms of GP).  But so far CGP is the only one we have code for.

(Personally, I rather like CGP, since it's resistant to bloat and pretty simple conceptually; but that's just my opinion)

**Comment by nbro** [comment]
@SigmaX One of the big limitations of current EC libraries is that they only support one implementation of GP, so they do not allow for the comparison of different implementations/versions of GP. It would really be nice to have a library that implements the most common versions of GP, i.e. tree-based, stack-based, CGP, etc. LEAP seems to be the newest serious player in the game, so it could support these different implementations. I'm not sure I will have the time to contribute to LEAP, but I will see in the future.

**Comment by SigmaX** [comment]
Thanks @nbro --- agreed.  The issues you raise are a big part of why we built LEAP.  We hope it can grow into a more general and flexible framework, supporting many paradigms and representations while keeping things simple.

Our impression has also been that many frameworks write themselves into a corner, so to speak, ultimately making it hard to do new things with them.  It takes quite a bit of peer review and team diversity to keep that from happening!

Right now "GP" is vaguely in our [roadmap](https://leap-gmu.readthedocs.io/en/latest/roadmap.html), once someone has bandwidth to work on it.  Having CGP is a start, but getting some basic tree-based GP is really the important box to check, since many people treat is as canonical.  And yes, after that something like PushGP and/or grammatical evolution would round it out.

**Comment by piprrr** [comment]
> ...
> Right now "GP" is vaguely in our [roadmap](https://leap-gmu.readthedocs.io/en/latest/roadmap.html), once someone has bandwidth to work on it. Having CGP is a start, but getting some basic tree-based GP is really the important box to check, since many people treat is as canonical. And yes, after that something like PushGP and/or grammatical evolution would round it out.

"Bandwidth" is the critical issue since it's pretty much the three of us working on this when we have the time at work.  Worse yet, development has been needs driven for @SigmaX and myself; i.e., we prioritize design implement functionality for which we have an immediate need for work projects.  However, as Siggy stated earlier, we do try for an open framework such that is easier to extend to accommodate various EC approaches.

If you're interested, we do have a Slack workspace, `leap-gmu.slack.com`, in which we discuss LEAP design and implementation topics; we also have a weekly scrum on Thursdays at 4pm, EST, modulo holidays, of course.  (So no meeting today! ;) ) I share the meeting link in Slack on Thursdays, but I can also add you to the formal invite that maintains the Google Meet link.

Speaking of tree representations, I think that might become a priority for version 0.6.0 because graph-based NNs are becoming popular at work, and LEAP is on the hook to support that in some way.  Naturally, once support for that is added, then tree-based GP becomes tenable.
